version: "3.9"
services:
  php-apache:
    ports:
      - "8885:80"
    build: './build/php'
    volumes:
      - ./src:/var/www/html
  mysql:
    ports:
      - "3307:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8886:80
volumes:
  app:
  dbData: